@startuml Get Single Car (GET Single)

header Get Single car diagram
footer Page %page% of %lastpage%
title "Get Single car (GET Single)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:cars" as routercars
participant "<<controllers>>\n:cars" as controllerscars
participant "<<model>>\n:car" as modelcar
database "<<MongoDB>>\n:cars" as carsDatabase

client->server ++:req.get('/cars/:id')
server->routercars ++:app.use('/cars',cars)
routercars -> controllerscars ++:getCar()
controllerscars->modelcar ++:findById(req.params.id)
modelcar ->carsDatabase ++: carSchema
carsDatabase --> modelcar --: car
controllerscars <-- modelcar --:car
controllerscars->client --:response

@enduml
